### ISSUE TITLE
serve only one JS file

### ISSUE THREAD

**Issue by ThaDafinser** [verekia/modern-js-stack-training#3]
> In order to use multiple files to develop, but serve only one JS file to the client app (saving expensive HTTP requests),

https://github.com/verekia/modern-js-stack-training/tree/master/7-client-browserify

Maybe you could update that part. When using HTTP/2 this is not ture anymore

**Comment by verekia** [comment]
Very good point! I updated that part:

"In a Node environment, you can freely `import` different files and Node will resolve these files using your filesystem. In a browser, there is no filesystem, and therefore your `import`s point to nowhere. In order for our entry point file `app.js` to retrieve the tree of imports it needs, we are going to "bundle" that entire tree of dependencies into one file. Browserify is a tool and package that does this."
