### ISSUE TITLE
peerDependencies problem

### ISSUE THREAD

**Issue by designrubenz** [verekia/modern-js-stack-training#4]
Hi and thanks for the great tutorial and the effort that you put into it, really like it!

Here is a problem I cannot solve myself:
Running `npm install --save-dev eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react` (Chapter 06) results in
```
npm WARN package.json node@1.0.0 No description
npm WARN package.json node@1.0.0 No repository field.
npm WARN package.json node@1.0.0 No README data
npm WARN peerDependencies The peer dependency eslint-plugin-import@^1.16.0 included from eslint-config-airbnb will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/Johannes/.nvm/versions/node/v4.5.0/bin/node" "/Users/Johannes/.nvm/versions/node/v4.5.0/bin/npm" "install" "--save-dev" "eslint" "eslint-config-airbnb" "eslint-plugin-import" "eslint-plugin-jsx-a11y" "eslint-plugin-react"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint-plugin-import@2.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb-base@8.0.0 wants eslint-plugin-import@^1.16.0
npm ERR! peerinvalid Peer eslint-config-airbnb@12.0.0 wants eslint-plugin-import@^1.16.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Johannes/Documents/3_code/node/npm-debug.log
```

How can I get past this error?

**Comment by designrubenz** [comment]
My friend and js-expert @ryppyy just showed me how to make this work. Basically, you need to specify the version of the eslint-plugin-import module, like so:
`npm install --save-dev eslint eslint-config-airbnb eslint-plugin-import@1.16.0 eslint-plugin-jsx-a11y eslint-plugin-react`

Works for me.

**Comment by verekia** [comment]
I see you are using Node v4.5.0. I had this kind of issue in 4.x, but not in 6.x+, maybe try upgrading? That should solve the issue :) In 6.x+ it doesn't crash when it finds unmet peer dependencies.
Your solution is good for 4.x though, thanks!
